spring:
  profiles:
    active:
    - dev
---
server:
  port: 9527
spring:
  application:
    name: ZUUL-GATEWAY
  profiles: zuul
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    instance-id: gateway-9527
    prefer-ip-address: false
zuul:
  routes:
    myUser.serviceId: user-provider #需要映射的服务名。自定义变量
    myUser.path: /myzuul/** #/wbUser/**这个路径的访问都路由到serverId服务处理 访问变成：http://localhost:9527/myzuul/provider/user/5
  ignored-services: user-provider # 忽略这个服务，如果要忽略所有的服务， “*”
  prefix: "/taurus" #统一前缀：如果有多个服务，我们还可以给服务取一个前缀：
